version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn test_T10.wsgi --bind 0.0.0.0:8000 -w 4
    volumes:
      - static_volume:/test_T10/staticfiles
      - media_volume:/test_T10/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    build: ./conf/nginx
    volumes:
      - static_volume:/test_T10/staticfiles
      - media_volume:/test_T10/mediafiles
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
