# Generated by Django 3.1.4 on 2020-12-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField()),
                ('active', models.BooleanField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DebitoAutomatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Requested'), ('CA', 'Canceled'), ('AP', 'Aprooved'), ('RJ', 'Rejected')], default='RE', max_length=2)),
            ],
        ),
    ]
