# Generated by Django 3.1.4 on 2020-12-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(default='Foo', max_length=300),
            preserve_default=False,
        ),
    ]
