# Generated by Django 3.1.4 on 2020-12-19 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_debitoautomatico'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitoAutomatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Requested'), ('CA', 'Canceled'), ('AP', 'Aprooved'), ('RJ', 'Rejected')], default='RE', max_length=2)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.conta')),
            ],
        ),
    ]
