# Generated by Django 3.1.4 on 2020-12-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201222_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='status',
            field=models.CharField(choices=[('RE', 'Requested'), ('CA', 'Canceled'), ('AP', 'Approved'), ('RJ', 'Rejected')], default='RE', max_length=2),
        ),
    ]
